[package]
name = "trgls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4"
rand_xoshiro = "0.6.0"
rand_core = "0.6.0"